name: Node.js CICD

on:
  push:  
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs: 

  compile:
    runs-on: Agent-1
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '23'

      - name: Frontend Syntax Check
        run: |
          cd client
          find . -name "*.js" -exec node --check {} +

      - name: Backend Syntax Check
        run: |
          cd api
          find . -name "*.js" -exec node --check {} +


  gitleaks:
    runs-on: Agent-1
    needs: compile
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Clean temp directory
        run: |
          sudo rm -rf /tmp/gitleaks*
          sudo rm -f /tmp/gitleaks.tmp

      - name: Run Gitleaks Scan
        uses: gitleaks/gitleaks-action@v2


  trivy_scan:
    runs-on: Agent-1
    needs: gitleaks
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Run Trivy Filesystem Scan
        uses: aquasecurity/trivy-action@0.20.0
        with:
          scan-type: fs
          scan-ref: .
          ignore-unfixed: true
          vuln-type: library
          severity: HIGH,CRITICAL

    sonar_frontend:
    runs-on: Agent-1
    needs: trivy_scan

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan (Frontend)
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: client
          args: >
            -Dsonar.projectKey=myorg_frontend
            -Dsonar.projectName=myorg_frontend
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}

    sonar_backend:
    runs-on: Agent-1
    needs: sonar_frontend

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: SonarQube Scan (Backend)
        uses: SonarSource/sonarqube-scan-action@v2
        with:
          projectBaseDir: api
          args: >
            -Dsonar.projectKey=myorg_backend
            -Dsonar.projectName=myorg_backend
            -Dsonar.sources=.
            -Dsonar.exclusions=**/node_modules/**,**/dist/**,**/build/**
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
          SONAR_HOST_URL: ${{ secrets.SONAR_HOST_URL }}
